### ISSUE TITLE
Don't sort files by filename

### ISSUE THREAD

**Issue by edyan** [ssato/python-anyconfig#124]
Hello,

I am trying to load multiple files with the `load` method I and noticed that the merge between them is not done properly. Instead of loading files in respect of the list, it sort the list then load it. Then if you load a `z.yaml` file then a `a.yaml` file, the second is loaded first and overridden by the first (instead of the opposite).

File `z.yaml`
```yaml
---

services:
  php:
    enabled: false
```

file `a.yaml`
```yaml
---

services:
  php:
    enabled: true
```

Command : `anyconfig_cli -T z.yaml a.yaml -O yaml` gives : 

```
services:
  php:
    enabled: false
```

This works with anyconfig 0.9.x but not with 0.10.x

**Comment by ssato** [comment]
You're right. It may be resolved by f921986.

**Comment by ssato** [comment]
I've released 0.11.0 and it may resolve your issue as far as I tested.
Could you please try that version?

**Comment by edyan** [comment]
hi, thanks for your reactivity. It seems that now I have a new problem : I have a certain amount of config files and a spec file to validate the concatenated files. 

Exemple
File z.yaml

```yaml
---

services:
  php:
    enabled: false
environment: dev

```yaml
file a.yaml

---

services:
  php:
    enabled: true
```

I say in my specs that I need to have "environment". And anyconfig tells me : `- 'environment' is a required property`

```yaml
---

"$schema": http://json-schema.org/draft-04/schema#
type: object
required:
  - environment
```
