### ISSUE TITLE
Preserve merge strategy with include

### ISSUE THREAD

**Issue by retr0h** [ssato/python-anyconfig#81]
Is there a way merge strategy can be applied to include?  When executing the following code:

```
import anyconfig
f1 = anyconfig.load("a.yml", ac_template=True)
f2 = anyconfig.load("b.yml", ac_template=True)

anyconfig.merge(f1, f2, ac_merge=anyconfig.MS_DICTS)
print f1
```

### a.yml

```
---
{% include 'included.yml' %}
a: 1
b:
   - c: 3
d:
   e: "bbb"
```

### b.yml

```
---
```

### included.yml

```
b:
   - c: 0
   - c: 2
d:
   e: "aaa"
   f: 3
```

The result should be:

`{'a': 1, 'b': [{'c': 3}], 'd': {'e': "bbb", 'f': 3}}`

However, the result is:

`{'a': 1, 'b': [{ 'c': 3}], 'd': {'e': 'bbb'}}`
